"""
Learning routes.

POST /api/learning/topic

Generate structured learning content for a topic and attach
curated external learning resources and YouTube learning videos.

Security:

    - Gemini API key is supplied per request.
    - Tavily API key is supplied per request.
    - API keys are never persisted or logged.
    - Learning generation is stateless and does not access
      session-owned user data.
    - Gemini failures prevent lesson generation.
    - Tavily failures do not prevent the generated lesson
      from being returned.
"""

from __future__ import annotations

import logging

from fastapi import (
    APIRouter,
    Header,
    HTTPException,
    status,
)

from app.models.requests import TopicRequest
from app.models.responses import LearningContent
from app.services.gemini_service import (
    GeminiAuthenticationError,
    GeminiQuotaError,
    gemini_service,
)
from app.services.resource_search_service import (
    ResourceSearchAuthenticationError,
    ResourceSearchQuotaError,
    resource_search_service,
)


logger = logging.getLogger(__name__)


router = APIRouter(
    prefix="/api/learning",
    tags=["Learning"],
)


# ============================================================================
# HELPERS
# ============================================================================


def _get_required_api_key(
    value: str | None,
    *,
    service_name: str,
    header_code: str,
) -> str:
    """
    Validate a request-scoped external API key.

    The key is intentionally never logged, persisted, or returned.
    """

    if not isinstance(
        value,
        str,
    ):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail={
                "error": (
                    f"{service_name} API key is required."
                ),
                "code": header_code,
            },
        )

    normalized = value.strip()

    if not normalized:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail={
                "error": (
                    f"{service_name} API key is required."
                ),
                "code": header_code,
            },
        )

    return normalized


# ============================================================================
# MAIN ENDPOINT
# ============================================================================


@router.post(
    "/topic",
    response_model=LearningContent,
    status_code=status.HTTP_200_OK,
)
def learn_topic(
    request: TopicRequest,
    x_gemini_api_key: str | None = Header(
        default=None,
        alias="X-Gemini-API-Key",
    ),
    x_tavily_api_key: str | None = Header(
        default=None,
        alias="X-Tavily-API-Key",
    ),
):
    """
    Generate structured learning content for a topic.

    This endpoint is intentionally stateless. It does not read or modify
    session-owned data, so X-BodhaQ-Session is not required.

    The Study response contains three independent sections:

        1. Explain
           Generated by Gemini.

        2. Resources
           Retrieved from Tavily.

        3. Videos
           Retrieved through a YouTube-focused Tavily search.

    Gemini and Tavily use request-scoped user-provided API keys.
    """

    # =========================================================================
    # REQUEST VALIDATION
    # =========================================================================

    topic = (
        request.topic.strip()
        if isinstance(
            request.topic,
            str,
        )
        else ""
    )

    if not topic:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail={
                "error": "Learning topic cannot be empty.",
                "code": "INVALID_LEARNING_REQUEST",
            },
        )

    # =========================================================================
    # API KEY VALIDATION
    # =========================================================================

    gemini_api_key = _get_required_api_key(
        x_gemini_api_key,
        service_name="Gemini",
        header_code="GEMINI_API_KEY_REQUIRED",
    )

    tavily_api_key = _get_required_api_key(
        x_tavily_api_key,
        service_name="Tavily",
        header_code="TAVILY_API_KEY_REQUIRED",
    )

    # =========================================================================
    # GENERATE STRUCTURED LESSON — EXPLAIN
    # =========================================================================

    try:
        result = gemini_service.generate_learning_content(
            topic=topic,
            api_key=gemini_api_key,
        )

    except GeminiAuthenticationError as exc:

        logger.warning(
            "[Learning] Gemini authentication failed."
        )

        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail={
                "error": (
                    "Gemini authentication failed. "
                    "Please check your API key."
                ),
                "code": "AI_AUTHENTICATION_FAILED",
            },
        ) from exc

    except GeminiQuotaError as exc:

        logger.warning(
            "[Learning] Gemini quota/rate limit reached."
        )

        raise HTTPException(
            status_code=status.HTTP_429_TOO_MANY_REQUESTS,
            detail={
                "error": (
                    "Gemini rate limit or quota reached. "
                    "Please try again later."
                ),
                "code": "AI_RATE_LIMIT",
            },
        ) from exc

    except ValueError as exc:

        logger.warning(
            "[Learning] Invalid Gemini request: %s",
            type(exc).__name__,
        )

        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail={
                "error": str(exc),
                "code": "INVALID_LEARNING_REQUEST",
            },
        ) from exc

    except RuntimeError as exc:

        logger.exception(
            "[Learning] Gemini generation failed."
        )

        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail={
                "error": (
                    "Learning generation service "
                    "is currently unavailable."
                ),
                "code": "AI_SERVICE_UNAVAILABLE",
            },
        ) from exc

    except Exception as exc:

        logger.exception(
            "[Learning] Unexpected Gemini failure."
        )

        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail={
                "error": (
                    "Unable to generate learning content."
                ),
                "code": "LEARNING_GENERATION_FAILED",
            },
        ) from exc

    # =========================================================================
    # SEARCH EXTERNAL LEARNING RESOURCES
    # =========================================================================
    #
    # Resource search is independent from Gemini generation.
    #
    # Tavily authentication/quota failures are reported to the client because
    # silently returning an empty list would make an invalid BYOK key look
    # like a successful search with no results.
    #
    # Other search failures remain non-fatal: the generated lesson is still
    # returned without external resources.
    # =========================================================================

    try:
        resources = resource_search_service.search_resources(
            topic=topic,
            api_key=tavily_api_key,
            max_results=8,
        )

    except ResourceSearchAuthenticationError as exc:

        logger.warning(
            "[Learning] Tavily authentication failed."
        )

        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail={
                "error": (
                    "Tavily authentication failed. "
                    "Please check your API key."
                ),
                "code": "SEARCH_AUTHENTICATION_FAILED",
            },
        ) from exc

    except ResourceSearchQuotaError as exc:

        logger.warning(
            "[Learning] Tavily quota/rate limit reached."
        )

        raise HTTPException(
            status_code=status.HTTP_429_TOO_MANY_REQUESTS,
            detail={
                "error": (
                    "Tavily rate limit or quota reached. "
                    "Please try again later."
                ),
                "code": "SEARCH_RATE_LIMIT",
            },
        ) from exc

    except Exception:

        logger.exception(
            "[Learning] Resource search failed. "
            "Returning lesson without external resources."
        )

        resources = []

    # =========================================================================
    # SEARCH YOUTUBE LEARNING VIDEOS
    # =========================================================================

    try:
        videos = resource_search_service.search_videos(
            topic=topic,
            api_key=tavily_api_key,
            max_results=8,
        )

    except ResourceSearchAuthenticationError as exc:

        logger.warning(
            "[Learning] Tavily authentication failed during video search."
        )

        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail={
                "error": (
                    "Tavily authentication failed. "
                    "Please check your API key."
                ),
                "code": "SEARCH_AUTHENTICATION_FAILED",
            },
        ) from exc

    except ResourceSearchQuotaError as exc:

        logger.warning(
            "[Learning] Tavily quota/rate limit reached "
            "during video search."
        )

        raise HTTPException(
            status_code=status.HTTP_429_TOO_MANY_REQUESTS,
            detail={
                "error": (
                    "Tavily rate limit or quota reached. "
                    "Please try again later."
                ),
                "code": "SEARCH_RATE_LIMIT",
            },
        ) from exc

    except Exception:

        logger.exception(
            "[Learning] Video search failed. "
            "Returning lesson without external videos."
        )

        videos = []

    # =========================================================================
    # BUILD RESPONSE
    # =========================================================================

    return LearningContent(
        topic=result.topic,
        definition=result.definition,
        key_concepts=result.key_concepts,
        example=result.example.model_dump(),
        important_points=result.important_points,
        resources=[
            {
                "title": resource.get(
                    "title",
                    "",
                ),
                "url": resource.get(
                    "url",
                    "",
                ),
                "description": resource.get(
                    "description",
                    "",
                ),
                "resource_type": resource.get(
                    "resource_type",
                    "",
                ),
                "domain": resource.get(
                    "domain",
                    "",
                ),
            }
            for resource in resources
            if isinstance(
                resource,
                dict,
            )
        ],
        videos=[
            {
                "title": video.get(
                    "title",
                    "",
                ),
                "url": video.get(
                    "url",
                    "",
                ),
                "thumbnail": video.get(
                    "thumbnail",
                ),
                "channel": video.get(
                    "channel",
                ),
                "description": video.get(
                    "description",
                    "",
                ),
                "duration": video.get(
                    "duration",
                ),
            }
            for video in videos
            if isinstance(
                video,
                dict,
            )
        ],
    )